server:
  port: 8080
  servlet:
    context-path: /

# better readable jackson serialization format
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # show the query
    properties: # show the query
      hibernate.format_sql: true
      
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jwt?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Media123
    #driver-class-name: com.mysql.jdbc.Driver

  devtools:
    restart:
      enabled: true

jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    #org.zerhusen.security: DEBUG
    org.springframework.security: DEBUG
    #root: OFF
    org.hibernate.type: trace # show the query value
      